puts "true && true is true: #{true && true}"
puts "false && true is false: #{false && true}"
puts "1 == 1 && 2 == 1 is false: #{1 == 1 && 2 == 1}"
puts "test == test is true: #{"test" == "test"}"
puts "1 == 1 || 2 != 1 is true: #{1 == 1 || 2 != 1}"
puts "true && 1 == 1 is true: #{true && 1 == 1}"
puts "false && 0 != 0 is false: #{false && 0 != 0}"
puts "true || 1 == 1 is true: #{true || 1 == 1}"
puts "test == testing is false: #{"test" == "testing"}"
puts "1 != 0 && 2 == 1 is false: #{1 != 0 && 2 == 1}"
puts "test != testing is true: #{"test" != "testing"}"
puts "test == 1 is false: #{"test" == 1}"
puts "!(true && false) is true: #{!(true && false)}"
puts "!(1 == 1 && 0 != 1) is false: #{!(1 == 1 && 0 != 1)}"
puts "!(10 == 1 || 1000 == 1000) is false: #{!(10 == 1 || 1000 == 1000)}"
puts "!(1 != 10 || 3 == 4) is false: #{!(1 != 10 || 3 == 4)}"
puts "!(testing == testing && Zed == Cool Guy) is true: #{!("testing" == "testing" && "Zed" == "Cool Guy")}"
puts "1 == 1 && (!(testing == 1 || 1 == 0)) is true: #{1 == 1 && (!("testing" == 1 || 1 == 0))}"
puts "chunky == bacon && (!(3 == 4 || 3 == 3)) is false: #{"chunky" == "bacon" && (!(3 == 4 || 3 == 3))}"
puts "3 == 3 && (!(testing == testing || Ruby == Fun)) is false: #{3 == 3 && (!("testing" == "testing" || "Ruby" == "Fun"))}"